FROM balena/open-balena-haproxy:v4.0.7

COPY certs/export/chain.pem /certs/export/chain.pem
COPY certs/export/chain.pem.key /certs/export/chain.pem.key
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
